<a href="https://colab.research.google.com/github/Narae-210/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
def phasor(x,y,z,w):
  # amp, sr, dur, freq
  %matplotlib inline
  from matplotlib import pyplot as plt
  import IPython.display as ipd
  import numpy as np
  from scipy.signal import lfilter
  t = np.arange(1, y * z +1 ) / y
  theta = t * 2 *np.pi * w
  s = np.sin(theta)
  return s, theta, t

In [25]:
phasor(1, 5000, 0.5, 200)

(array([ 2.48689887e-01,  4.81753674e-01,  6.84547106e-01, ...,
        -4.81753674e-01, -2.48689887e-01,  3.92877345e-15]),
 array([2.51327412e-01, 5.02654825e-01, 7.53982237e-01, ...,
        6.27815876e+02, 6.28067203e+02, 6.28318531e+02]),
 array([2.000e-04, 4.000e-04, 6.000e-04, ..., 4.996e-01, 4.998e-01,
        5.000e-01]))